// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package pmark

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type markEvent struct {
	_         structs.HostLayout
	Type      uint32
	_         [4]byte
	Key       markProcessKey
	ParentKey markProcessKey
	Pid       uint32
	Ppid      uint32
	HasMark   bool
	_         [7]byte
	Value     markProcessValue
	Comm      [16]int8
}

type markProcessKey struct {
	_         structs.HostLayout
	Tgid      uint32
	_         [4]byte
	StartTime uint64
}

type markProcessValue struct {
	_           structs.HostLayout
	Tombstone   bool
	Inheritance bool
	HasMark     bool
	Priority    int8
	_           [4]byte
	Generation  uint64
	Mark        uint64
	Timestamp   uint64
}

// loadMark returns the embedded CollectionSpec for mark.
func loadMark() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MarkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load mark: %w", err)
	}

	return spec, err
}

// loadMarkObjects loads mark and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*markObjects
//	*markPrograms
//	*markMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMarkObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMark()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// markSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type markSpecs struct {
	markProgramSpecs
	markMapSpecs
	markVariableSpecs
}

// markProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type markProgramSpecs struct {
	HandleSchedProcessExec *ebpf.ProgramSpec `ebpf:"handle_sched_process_exec"`
	HandleSchedProcessExit *ebpf.ProgramSpec `ebpf:"handle_sched_process_exit"`
	HandleSchedProcessFork *ebpf.ProgramSpec `ebpf:"handle_sched_process_fork"`
}

// markMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type markMapSpecs struct {
	Events    *ebpf.MapSpec `ebpf:"events"`
	Processes *ebpf.MapSpec `ebpf:"processes"`
}

// markVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type markVariableSpecs struct {
}

// markObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type markObjects struct {
	markPrograms
	markMaps
	markVariables
}

func (o *markObjects) Close() error {
	return _MarkClose(
		&o.markPrograms,
		&o.markMaps,
	)
}

// markMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type markMaps struct {
	Events    *ebpf.Map `ebpf:"events"`
	Processes *ebpf.Map `ebpf:"processes"`
}

func (m *markMaps) Close() error {
	return _MarkClose(
		m.Events,
		m.Processes,
	)
}

// markVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type markVariables struct {
}

// markPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type markPrograms struct {
	HandleSchedProcessExec *ebpf.Program `ebpf:"handle_sched_process_exec"`
	HandleSchedProcessExit *ebpf.Program `ebpf:"handle_sched_process_exit"`
	HandleSchedProcessFork *ebpf.Program `ebpf:"handle_sched_process_fork"`
}

func (p *markPrograms) Close() error {
	return _MarkClose(
		p.HandleSchedProcessExec,
		p.HandleSchedProcessExit,
		p.HandleSchedProcessFork,
	)
}

func _MarkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mark_bpfel.o
var _MarkBytes []byte
