// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package fwmark

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type fwmarkProcessKey struct {
	_         structs.HostLayout
	Tgid      uint32
	_         [4]byte
	StartTime uint64
}

type fwmarkProcessValue struct {
	_           structs.HostLayout
	Tombstone   bool
	Inheritance bool
	HasMark     bool
	Priority    int8
	_           [4]byte
	Generation  uint64
	Mark        uint64
	Timestamp   uint64
}

// loadFwmark returns the embedded CollectionSpec for fwmark.
func loadFwmark() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FwmarkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load fwmark: %w", err)
	}

	return spec, err
}

// loadFwmarkObjects loads fwmark and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*fwmarkObjects
//	*fwmarkPrograms
//	*fwmarkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFwmarkObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFwmark()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// fwmarkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fwmarkSpecs struct {
	fwmarkProgramSpecs
	fwmarkMapSpecs
	fwmarkVariableSpecs
}

// fwmarkProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fwmarkProgramSpecs struct {
	FwmarkSockCreate *ebpf.ProgramSpec `ebpf:"fwmark_sock_create"`
}

// fwmarkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fwmarkMapSpecs struct {
	Processes *ebpf.MapSpec `ebpf:"processes"`
}

// fwmarkVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fwmarkVariableSpecs struct {
}

// fwmarkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFwmarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type fwmarkObjects struct {
	fwmarkPrograms
	fwmarkMaps
	fwmarkVariables
}

func (o *fwmarkObjects) Close() error {
	return _FwmarkClose(
		&o.fwmarkPrograms,
		&o.fwmarkMaps,
	)
}

// fwmarkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFwmarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type fwmarkMaps struct {
	Processes *ebpf.Map `ebpf:"processes"`
}

func (m *fwmarkMaps) Close() error {
	return _FwmarkClose(
		m.Processes,
	)
}

// fwmarkVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFwmarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type fwmarkVariables struct {
}

// fwmarkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFwmarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type fwmarkPrograms struct {
	FwmarkSockCreate *ebpf.Program `ebpf:"fwmark_sock_create"`
}

func (p *fwmarkPrograms) Close() error {
	return _FwmarkClose(
		p.FwmarkSockCreate,
	)
}

func _FwmarkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed fwmark_bpfeb.o
var _FwmarkBytes []byte
